### ISSUE TITLE
repairwheel cannot find library that auditwheel can

### ISSUE THREAD

**Issue by daniel-larraz** [jvolkman/repairwheel#31]
I'm trying to repair a wheel that includes a C++ (Cython) extension on an Ubuntu 20.04 system. The extension depends on the GMP library, which is installed on the standard path. When I run `auditwheel repair foo-cp38-cp38-linux_x86_64.whl --plat manylinux_2_31_x86_64`, it works fine. However, when I run `repairwheel foo-cp38-cp38-linux_x86_64.whl -o wheelout`, I get the following error:

```
foo-cp38-cp38-linux_x86_64.whl is consistent with the following
platform tag: "linux_x86_64".

The wheel references external versioned symbols in these
system-provided shared libraries: libgcc_s.so.1 with versions
{'GCC_3.0'}, libpthread.so.0 with versions {'GLIBC_2.2.5'}, libc.so.6
with versions {'GLIBC_2.3.4', 'GLIBC_2.4', 'GLIBC_2.14', 'GLIBC_2.7',
'GLIBC_2.2.5'}, libstdc++.so.6 with versions {'CXXABI_1.3.5',
'GLIBCXX_3.4.18', 'CXXABI_1.3.9', 'GLIBCXX_3.4.9', 'GLIBCXX_3.4.26',
'GLIBCXX_3.4.15', 'CXXABI_1.3.8', 'GLIBCXX_3.4.19', 'GLIBCXX_3.4',
'GLIBCXX_3.4.20', 'CXXABI_1.3.7', 'GLIBCXX_3.4.22', 'CXXABI_1.3',
'GLIBCXX_3.4.21', 'GLIBCXX_3.4.14', 'GLIBCXX_3.4.11'}, libm.so.6 with
versions {'GLIBC_2.29'}

This constrains the platform tag to "manylinux_2_31_x86_64". In order
to achieve a more compatible tag, you would need to recompile a new
wheel from source on a system with earlier versions of these
libraries, such as a recent manylinux image.
Traceback (most recent call last):
  File "/home/daniel/.local/bin/repairwheel", line 8, in <module>
    sys.exit(main())
  File "/home/daniel/.local/lib/python3.8/site-packages/repairwheel/repair.py", line 102, in main
    fn(original_wheel, temp_wheel_dir, lib_path)
  File "/home/daniel/.local/lib/python3.8/site-packages/repairwheel/linux/repair.py", line 67, in repair
    repair_args.func(repair_args, repair_parser)
  File "/home/daniel/.local/lib/python3.8/site-packages/repairwheel/_vendor/auditwheel/main_repair.py", line 175, in execute
    out_wheel = repair_wheel(
  File "/home/daniel/.local/lib/python3.8/site-packages/repairwheel/_vendor/auditwheel/repair.py", line 79, in repair_wheel
    raise ValueError(
ValueError: Cannot repair wheel, because required library "libgmp.so.10" could not be located
```

If I explicitly pass the path to the library as follows `repairwheel foo-cp38-cp38-linux_x86_64.whl -o wheelout -l /usr/lib/x86_64-linux-gnu/`, it works fine. However, I was expecting repairwheel to find the library without having to specify the path manually.

Thank you for this useful tool!

**Comment by jvolkman** [comment]
Thanks.

It explicitly does not look in the normal locations because the tool targets cross-platform repair use cases. I.e., `/usr/lib/x86_64-linux-gnu` doesn't exist if I'm build and repairing the wheel on macos.

I supposed there could be something like `--default-host-lib-paths` (or some better name) that would include the default paths for the host.

**Comment by daniel-larraz** [comment]
PR #32 fixes this issue. It should not affect the macOS and Windows platforms.

**Comment by daniel-larraz** [comment]
@jvolkman Do you have any feedback on the proposed change? I'm happy to explore alternative solutions if needed. I tested repairing a Linux wheel on macOS and Windows, and it worked fine.

**Comment by jvolkman** [comment]
Thanks @daniel-larraz. While thinking about this, it occurred to me that the other reason I cleared the default paths is because they may lead to non-reproducible results. I use this tool in a [Bazel ruleset](https://github.com/jvolkman/rules_pycross), and in general Bazel tools need to define all inputs. So the tool only looks for inputs in paths that are explicitly specified.

I can think of a few options:
1. Include the system paths by default, and add a `--no-sys-path` option (or whatever). This is a breaking change, so I'd prefer not to do this.
2. Don't include the system paths by default, but add a `--sys-paths` option (or whatever).
3. Some hybrid approach like: default to the system paths, but any instance of `--lib-dir` will clear that default list and use only what is specified.

**Comment by daniel-larraz** [comment]
Thank you very much for your feedback, @jvolkman.

I personally prefer not having to pass an additional option to include the default paths. The rationale is that this would match the expected behavior of the users of the individual repair tools. In fact, `delvewheel` uses the `PATH` environment variable to search for DLL dependencies, and repairwheel doesn't clear this variable. Changing this would also result in a breaking change. However, extending the number of paths the tool looks for libraries seems less disruptive than reducing them.

One thing I could do to make the result more reproducible is to append the list of user-defined paths at the beginning of the list (as opposed to the end) so that they have higher priority than the default paths. This way, the tool would only rely on the default paths if a library cannot be found in the paths provided by the user. I can apply a similar change for macOS [here](https://github.com/jvolkman/repairwheel/blob/main/src/repairwheel/macos/repair.py#L38).

Since any solution we adopt is going to be a breaking change, I would go with the `--no-sys-path` option. This would make repairwheel have behavior closer to the other repair tools by default, while still providing the flexibility to make the results more reproducible if needed.

**Comment by daniel-larraz** [comment]
Will do. Thank you!
